-- CARSERVICE.BZ_MASTER_GL definition

CREATE TABLE "BZ_MASTER_GL" 
   (	"GL_NO" TEXT PRIMARY KEY, 
	"GL_DESC" TEXT, 
	"TOKEN" TEXT, 
	"USERSTATUS" INTEGER,
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
-- CARSERVICE.BZ_MASTER_IO definition

CREATE TABLE "BZ_MASTER_IO" 
   (	
    "IO" TEXT PRIMARY KEY, 
	"IO_DESC" TEXT, 
	"IO_TYPE" TEXT, 
	"COST_CENTER_RESP" TEXT, 
	"COM_CODE" TEXT, 
	"CURRENCY" TEXT, 
	"IO_CATE" TEXT, 
	"TOKEN" TEXT, 
	"USERSTATUS" INTEGER DEFAULT 1,
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
-- CARSERVICE.BZ_USERS definition

CREATE TABLE "BZ_USERS" 
   (	
   "EMPLOYEEID" TEXT PRIMARY KEY, 
	"USERID" TEXT, 
	"COMPANYCODE" TEXT, 
	"FUNCTION" TEXT, 
	"DEPARTMENT" TEXT, 
	"DIVISION" TEXT, 
	"SECTIONS" TEXT, 
	"UNITS" TEXT, 
	"ORGID" TEXT, 
	"POSID" TEXT, 
	"OBJENFULLNAME" TEXT, 
	"OBJTHFULLNAME" TEXT, 
	"POSCAT" TEXT, 
	"EMPSTATUS" TEXT, 
	"EMPCAT" TEXT, 
	"PERSAREA" TEXT, 
	"PERSUBAREA" TEXT, 
	"EMPGROUP" TEXT, 
	"EMPSUBGROUP" TEXT, 
	"THNAME" TEXT, 
	"THTITLE" TEXT, 
	"THFIRSTNAME" TEXT, 
	"THLASTNAME" TEXT, 
	"ENTITLE" TEXT, 
	"ENFIRSTNAME" TEXT, 
	"ENLASTNAME" TEXT, 
	"GENDER" TEXT, 
	"REFERENCEID" TEXT, 
	"EMAIL" TEXT, 
	"SUPERVISOR" TEXT, 
	"MANAGERIAL" TEXT, 
	"CONTRACT" TEXT, 
	"HOLDERPOSITION" TEXT, 
	"REPORTTOPOS" TEXT, 
	"REPORTTOID" TEXT, 
	"REPORTTONAME" TEXT, 
	"REPORTTOEMAIL" TEXT, 
	"TOKEN" TEXT, 
	"IMGURL" TEXT, 
	"ORGNAME" TEXT, 
	"MANAGER_EMPID" TEXT, 
	"SH" TEXT, 
	"VP" TEXT, 
	"AEP" TEXT, 
	"EVP" TEXT, 
	"SEVP" TEXT, 
	"CEO" TEXT, 
	"COSTCENTER" TEXT, 
	"USERSTATUS" INTEGER DEFAULT 1, 
	"ACTION" TEXT, 
	"ACTION_DATE" TEXT, 
	
	"ROLE_ID" INTEGER, 
	"EMPPOS" TEXT, 
	"ORDERWBS" TEXT, 
	"GLACCOUNT" TEXT, 
	"USERTYPE" TEXT, 
	"HIREDATE" TEXT,
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);

-- CARSERVICE.CARS_APPROVER definition

CREATE TABLE "CARS_APPROVER" 
   (	"ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"APPROVER_USERNAME" TEXT, 
	"APPROVER_ACTION" INTEGER, 
	"APPROVER_REASON" TEXT, 
	"APPROVER_ACTION_DATE" TEXT, 
	"ADMIN_USERNAME" TEXT, 
	"ADMIN_ACTION" INTEGER, 
	"ADMIN_REASON" TEXT, 
	"ADMIN_ACTION_DATE" TEXT,
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
-- CARSERVICE.CARS_APPROVER_DETAIL definition

CREATE TABLE "CARS_APPROVER_DETAIL" 
   (	"ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"APPROVER_USERNAME" TEXT, 
	"APPROVER_ACTION" INTEGER, 
	"APPROVED_DATE" TEXT, 
	"ADMIN_ASSIGN_USERNAME" TEXT, 
	"ADMIN_ACTION" INTEGER, 
	"ASSIGN_DATE" TEXT, 
	"SUBMIT_USERNAME" TEXT, 
	"SUBMIT_DATE" TEXT,
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT

);
CREATE INDEX "APPROVER_DETAIL_IDX" ON "CARS_APPROVER_DETAIL" ("ID");
-- CARSERVICE.CARS_AUTHORIZATION definition

CREATE TABLE "CARS_AUTHORIZATION" 
   (	
	"ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
    "USERNAME" TEXT, 
	"SUPER_ADMIN" TEXT, 
	"PMSV_ADMIN" TEXT, 
	"GSBO_ADMIN" TEXT, 
	"TEMP_2" TEXT, 
	"TEMP_3" TEXT, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
-- CARSERVICE.CARS_CALENDAR_EVENT definition

CREATE TABLE "CARS_CALENDAR_EVENT" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"ITEM_NO" INTEGER, 
	"DOC_NO" TEXT, 
	"BOOKING_ID" INTEGER, 
	"DRIVER_CODE" TEXT, 
	"DRIVER_NAME" TEXT, 
	"DATE_START" TEXT, 
	"DATE_END" TEXT, 
	"LOCATION_FROM" TEXT, 
	"LOCATION_TO" TEXT, 
	"TIME_START" TEXT, 
	"TIME_END" TEXT, 
	"TRANSPORT_TYPE" INTEGER, 
	"TRAVELOR_ID" TEXT, 
	"TRAVELOR_NAME" TEXT, 
	"TEL_NUMBER" TEXT, 
	"DETAIL" TEXT, 
	"CARCOMP_CODE" INTEGER, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT, 
	"BOOKING_ITEM_NO" INTEGER, 
	"ASSIGN_ROUTE" INTEGER
);
-- CARSERVICE.CARS_DETAIL_BOOKING definition

CREATE TABLE "CARS_DETAIL_BOOKING" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"ITEM_NO" INTEGER, 
	"CAR_TYPE" INTEGER, 
	"REQ_TYPE" INTEGER, 
	"BUSINESS_DOC_NO" TEXT, 
	"REQ_FOR" TEXT, 
	"REQ_FROM" INTEGER, 
	"USE_DATE_FROM" TEXT, 
	"USE_DATE_TO" TEXT, 
	"USE_TIME_FROM" TEXT, 
	"USE_TIME_TO" TEXT, 
	"LOCATION_FROM" TEXT, 
	"LOCATON_FROM_URL" TEXT, 
	"LOCATON_TO" TEXT, 
	"LOCATON_TO_URL" TEXT, 
	"TRANSPORT_TYPE" INTEGER, 
	"TRANSPORT_DETAIL" TEXT, 
	"CREATE_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"USER_CREATE" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT, 
	"ORDER_BY" INTEGER 
);
CREATE INDEX "DETAIL_BOOKING_IDX" ON "CARS_DETAIL_BOOKING" ("REQ_TYPE", "ITEM_NO", "REQ_FROM", "CAR_TYPE");
-- CARSERVICE.CARS_DETAIL_REQ definition

CREATE TABLE "CARS_DETAIL_REQ" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"DOC_NO" TEXT, 
	"REQ_USER_NAME" TEXT, 
	"REQ_USER_DISPLAY" TEXT, 
	"REQ_IDICATOR" TEXT, 
	"REQ_TEL_NUMBER" TEXT, 
	"ON_BEHALF_OF" TEXT, 
	"OBH_EMP_ID" TEXT, 
	"OBH_USER_NAME" TEXT, 
	"OBH_IDICATOR" TEXT, 
	"OBH_TEL_NUMBER" TEXT, 
	"PROJECT_WORK" TEXT, 
	"ACCOUNT_CODE" TEXT, 
	"COST_CENTER" TEXT, 
	"IO_NO" TEXT, 
	"COST_COMP" INTEGER, 
	"CREATE_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
CREATE INDEX "DETAIL_REQ_IDX" ON "CARS_DETAIL_REQ" ("ID", "COST_COMP");
-- CARSERVICE.CARS_DETAIL_TRAVELER definition

CREATE TABLE "CARS_DETAIL_TRAVELER" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,  
	"ITEM_NO_BOOKING" INTEGER, 
	"NO_DISP" INTEGER, 
	"UMS_ID" TEXT, 
	"UMS_USERNAME" TEXT, 
	"TEL_NUMBER" TEXT, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
CREATE INDEX "DETAIL_TRAVELER_IDX" ON "CARS_DETAIL_TRAVELER" ("ID", "ITEM_NO_BOOKING");
-- CARSERVICE.CARS_FEEDBACK definition

CREATE TABLE "CARS_FEEDBACK" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"COMPLACENCY" INTEGER, 
	"COMPLACENCY_DESCRIPTION" TEXT, 
	"SUGGESTION" TEXT, 
	"TEMP_1" TEXT, 
	"TEMP_2" TEXT, 
	"TEMP_3" TEXT, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
CREATE INDEX "FEEDBACK_IDX" ON "CARS_FEEDBACK" ("ID");
-- CARSERVICE.CARS_LOGIN_LOG definition

CREATE TABLE "CARS_LOGIN_LOG" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"USERNAME" TEXT, 
	"EMAIL" TEXT, 
	"LOGIN_DATE" TEXT, 
	"USERDISPLAY" TEXT,
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT

);
CREATE INDEX "LOGIN_LOG_IDX" ON "CARS_LOGIN_LOG" ("USERNAME", "EMAIL", "LOGIN_DATE");
-- CARSERVICE.CARS_MT_CARCOMP definition

CREATE TABLE "CARS_MT_CARCOMP" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"NAME" TEXT, 
	"SHORT_NAME" TEXT, 
	"CARS_FROM" TEXT, 
	"COORDINATOR" TEXT, 
	"EMAIL" TEXT, 
	"ORDER_BY" INTEGER, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT, 
	"TEL_NO" TEXT
);
CREATE INDEX "MT_CARCOMP_IDX" ON "CARS_MT_CARCOMP" ("ID");
-- CARSERVICE.CARS_MT_CARFROM definition

CREATE TABLE "CARS_MT_CARFROM" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"NAME" TEXT, 
	"ORDER_BY" INTEGER, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
CREATE INDEX "MT_CARFROM_IDX" ON "CARS_MT_CARFROM" ("ID");
-- CARSERVICE.CARS_MT_CARTYPE definition

CREATE TABLE "CARS_MT_CARTYPE" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"NAME" TEXT, 
	"ORDER_BY" INTEGER, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
-- CARSERVICE.CARS_MT_COMP definition

CREATE TABLE "CARS_MT_COMP" 
   (	"ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"COMP_CODE" TEXT, 
	"COMP_SHORT_NAME" TEXT, 
	"COMP_NAME" TEXT, 
	"ORDER_BY" INTEGER, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
CREATE INDEX "MT_COMP_IDX" ON "CARS_MT_COMP" ("ID");
-- CARSERVICE.CARS_MT_DRIVER definition

CREATE TABLE "CARS_MT_DRIVER" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"CARCOMP_CODE" INTEGER, 
	"CARS_FROM" TEXT, 
	"DRIVER_CODE" TEXT, 
	"DRIVER_NAME" TEXT, 
	"CARS_TYPE" INTEGER, 
	"CAR_MODEL" TEXT, 
	"CAR_COLOR" TEXT, 
	"VEHICLE_REGISTRATION" TEXT, 
	"TEL_NUMBER" TEXT, 
	"TEMP_1" TEXT, 
	"TEMP_2" TEXT, 
	"TEMP_3" TEXT, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT,
	"INACTIVE" TEXT
);
CREATE INDEX "MT_DRIVER_IDX" ON "CARS_MT_DRIVER" ("ID");
-- CARSERVICE.CARS_MT_SERVICE definition

CREATE TABLE "CARS_MT_SERVICE" 
   (	"ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"NAME" TEXT, 
	"ORDER_BY" INTEGER, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
CREATE INDEX "MT_SERVICE_IDX" ON "CARS_MT_SERVICE" ("ID");
-- CARSERVICE.CARS_MT_STATUS definition

CREATE TABLE "CARS_MT_STATUS" 
   (	"ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"NAME" TEXT, 
	"ORDER_BY" INTEGER, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
CREATE INDEX "MT_STATUS_IDX" ON "CARS_MT_STATUS" ("ID");
-- CARSERVICE.CARS_MT_STEP definition

CREATE TABLE "CARS_MT_STEP" 
   (	"ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"NAME" TEXT, 
	"ORDER_BY" INTEGER, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
CREATE INDEX "MT_STEP_IDX" ON "CARS_MT_STEP" ("ID");
-- CARSERVICE.CARS_ROUTE definition

CREATE TABLE "CARS_ROUTE" 
   (	"ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"ITEM_NO" INTEGER NOT NULL, 
	"ROUTE" INTEGER, 
	"CARCOMP_CODE" INTEGER, 
	"CARCOMP_NAME" TEXT, 
	"DRIVER_CODE" INTEGER, 
	"DRIVER_NAME" TEXT, 
	"CARS_TYPE_NAME" TEXT, 
	"CAR_MODEL" TEXT, 
	"CAR_COLOR" TEXT, 
	"VEHICLE_REGISTRATION" TEXT, 
	"TEL_NUMBER" TEXT, 
	"ORDER_BY" INTEGER, 
	"TEMP_1" TEXT, 
	"TEMP_2" TEXT, 
	"TEMP_3" TEXT, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT
);
CREATE INDEX "ROUTE_IDX" ON "CARS_ROUTE" ("ID", "ITEM_NO", "CARCOMP_CODE", "DRIVER_CODE");
-- CARSERVICE.CARS_USER_PROFILE definition

CREATE TABLE "CARS_USER_PROFILE" 
   (	
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
	"USERNAME" TEXT, 
	"EMP_ID" TEXT, 
	"ADDRESS" TEXT, 
	"ADDRESS_URL" TEXT, 
	"TEL_NO" TEXT, 
	"IMG_NAME" TEXT, 
	"IMG_PATH" TEXT, 
	"STATUS_UPLOAD_IMG" TEXT, 
	"ADDRESS2" TEXT, 
	"ADDRESS3" TEXT, 
	"ADDRESS4" TEXT,
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT 
);
-- CARSERVICE.CARS_WF_PROCESS definition

CREATE TABLE "CARS_WF_PROCESS" 
   (	"ID" INTEGER PRIMARY KEY AUTOINCREMENT, 
	"DOC_NO" TEXT, 
	"CAR_TYPE" INTEGER, 
	"YEAR" INTEGER, 
	"MONTH" INTEGER, 
	"RUNNING_NO" INTEGER, 
	"STEP_FLOW" INTEGER, 
	"STATUS_FLOW" INTEGER, 
	"CARS_FROM_CODE" TEXT, 
	"TEMP_2" TEXT, 
	"TEMP_3" TEXT, 
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" TEXT, 
	"UPDATED_DATE" TEXT, 
	"UPDATED_BY" TEXT 
);
CREATE INDEX "WF_PROCESS_IDX" ON "CARS_WF_PROCESS" ("DOC_NO", "CAR_TYPE", "YEAR", "MONTH", "RUNNING_NO", "STEP_FLOW", "STATUS_FLOW", "CARS_FROM_CODE");

